# courtesy of https://github.com/bradtraversy/docker-node-mongo

version: '3'

services:
  app:
    container_name: crypto-exchange
    build: .
    ports:
      - '89:3000'
      - '3002:3003'
    volumes:
      - ../../:/usr/src/app/
      - ./run.sh:/run.sh
      - app-node-modules:/usr/src/app/node_modules/

volumes:
  app-node-modules: